In [2]:
import pandas as pd

In [4]:
df = pd.read_excel('..\data\问题一.xlsx', engine='openpyxl')
df

,单品编码,单品名称,单品分类编码,分类名称,分类编码,销售单品编码
0,1.029000e+14,牛首生菜,1.011010e+09,花叶类,1.011010e+09,102900005117056
1,1.029000e+14,四川红香椿,1.011010e+09,水生根茎类,1.011010e+09,102900005115960
2,1.029000e+14,本地小毛白菜,1.011010e+09,茄类,1.011011e+09,102900005117056
3,1.029000e+14,白菜苔,1.011010e+09,辣椒类,1.011011e+09,102900005115823
4,1.029000e+14,苋菜,1.011010e+09,食用菌,1.011011e+09,102900005115908
...,...,...,...,...,...,...
878498,NaN,NaN,NaN,NaN,NaN,102900005115250
878499,NaN,NaN,NaN,NaN,NaN,102900011022764
878500,NaN,NaN,NaN,NaN,NaN,102900005115250
878501,NaN,NaN,NaN,NaN,NaN,102900011016701
878502,NaN,NaN,NaN,NaN,NaN,102900011022764